// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs_sLeDpZs0g7GH8dX075CU26JOQwyTE0',
    appId: '1:732007899853:web:dc9c0c0fb83d1c3fecbf84',
    messagingSenderId: '732007899853',
    projectId: 'spotify03',
    authDomain: 'spotify03.firebaseapp.com',
    storageBucket: 'spotify03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpSKjD-YFVeaINGD3-0vz3xKkZZNqP-0g',
    appId: '1:732007899853:android:90e349fd053344eaecbf84',
    messagingSenderId: '732007899853',
    projectId: 'spotify03',
    storageBucket: 'spotify03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCCYPNIKA3OHE3JpfNJk_bbQ9ohvA4cuI',
    appId: '1:732007899853:ios:6802abe4c8ad6105ecbf84',
    messagingSenderId: '732007899853',
    projectId: 'spotify03',
    storageBucket: 'spotify03.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCCYPNIKA3OHE3JpfNJk_bbQ9ohvA4cuI',
    appId: '1:732007899853:ios:6802abe4c8ad6105ecbf84',
    messagingSenderId: '732007899853',
    projectId: 'spotify03',
    storageBucket: 'spotify03.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs_sLeDpZs0g7GH8dX075CU26JOQwyTE0',
    appId: '1:732007899853:web:054714306764e175ecbf84',
    messagingSenderId: '732007899853',
    projectId: 'spotify03',
    authDomain: 'spotify03.firebaseapp.com',
    storageBucket: 'spotify03.appspot.com',
  );
}
